#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iperf
Version  : 3.13
Release  : 25
URL      : https://github.com/esnet/iperf/archive/3.13/iperf-3.13.tar.gz
Source0  : https://github.com/esnet/iperf/archive/3.13/iperf-3.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: iperf-bin = %{version}-%{release}
Requires: iperf-lib = %{version}-%{release}
Requires: iperf-license = %{version}-%{release}
Requires: iperf-man = %{version}-%{release}
BuildRequires : openssl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
iperf3:  A TCP, UDP, and SCTP network bandwidth measurement tool
================================================================

%package bin
Summary: bin components for the iperf package.
Group: Binaries
Requires: iperf-license = %{version}-%{release}

%description bin
bin components for the iperf package.


%package dev
Summary: dev components for the iperf package.
Group: Development
Requires: iperf-lib = %{version}-%{release}
Requires: iperf-bin = %{version}-%{release}
Provides: iperf-devel = %{version}-%{release}
Requires: iperf = %{version}-%{release}

%description dev
dev components for the iperf package.


%package lib
Summary: lib components for the iperf package.
Group: Libraries
Requires: iperf-license = %{version}-%{release}

%description lib
lib components for the iperf package.


%package license
Summary: license components for the iperf package.
Group: Default

%description license
license components for the iperf package.


%package man
Summary: man components for the iperf package.
Group: Default

%description man
man components for the iperf package.


%prep
%setup -q -n iperf-3.13
cd %{_builddir}/iperf-3.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1677008454
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1677008454
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iperf
cp %{_builddir}/iperf-%{version}/docs/_esnet/LICENSE %{buildroot}/usr/share/package-licenses/iperf/2710606f6db128e7cf24e84572811bbf177a4ce9 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iperf3

%files dev
%defattr(-,root,root,-)
/usr/include/iperf_api.h
/usr/lib64/libiperf.so
/usr/share/man/man3/libiperf.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libiperf.so.0
/usr/lib64/libiperf.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iperf/2710606f6db128e7cf24e84572811bbf177a4ce9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/iperf3.1
