#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iperf
Version  : 2.0.5
Release  : 2
URL      : http://downloads.sourceforge.net/project/iperf/iperf-2.0.5.tar.gz
Source0  : http://downloads.sourceforge.net/project/iperf/iperf-2.0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : NCSA
Requires: iperf-bin
Requires: iperf-doc

%description
This is Iperf v2.0.0, a tool for measuring Internet bandwidth performance.
See the doc directory for more documentation.
Briefly:

%package bin
Summary: bin components for the iperf package.
Group: Binaries

%description bin
bin components for the iperf package.


%package doc
Summary: doc components for the iperf package.
Group: Documentation

%description doc
doc components for the iperf package.


%prep
%setup -q -n iperf-2.0.5

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iperf

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
