#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iperf
Version  : 3.7
Release  : 19
URL      : https://github.com/esnet/iperf/archive/3.7/iperf-3.7.tar.gz
Source0  : https://github.com/esnet/iperf/archive/3.7/iperf-3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-LBNL
Requires: iperf-bin = %{version}-%{release}
Requires: iperf-lib = %{version}-%{release}
Requires: iperf-license = %{version}-%{release}
Requires: iperf-man = %{version}-%{release}
BuildRequires : openssl-dev

%description
iperf3:  A TCP, UDP, and SCTP network bandwidth measurement tool
================================================================

%package bin
Summary: bin components for the iperf package.
Group: Binaries
Requires: iperf-license = %{version}-%{release}

%description bin
bin components for the iperf package.


%package dev
Summary: dev components for the iperf package.
Group: Development
Requires: iperf-lib = %{version}-%{release}
Requires: iperf-bin = %{version}-%{release}
Provides: iperf-devel = %{version}-%{release}
Requires: iperf = %{version}-%{release}

%description dev
dev components for the iperf package.


%package lib
Summary: lib components for the iperf package.
Group: Libraries
Requires: iperf-license = %{version}-%{release}

%description lib
lib components for the iperf package.


%package license
Summary: license components for the iperf package.
Group: Default

%description license
license components for the iperf package.


%package man
Summary: man components for the iperf package.
Group: Default

%description man
man components for the iperf package.


%prep
%setup -q -n iperf-3.7
cd %{_builddir}/iperf-3.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579207367
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1579207367
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iperf
cp %{_builddir}/iperf-3.7/LICENSE %{buildroot}/usr/share/package-licenses/iperf/035196a90af9ebe90871eb93aae845f5367247f3
cp %{_builddir}/iperf-3.7/docs/_esnet/LICENSE %{buildroot}/usr/share/package-licenses/iperf/2710606f6db128e7cf24e84572811bbf177a4ce9
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iperf3

%files dev
%defattr(-,root,root,-)
/usr/include/iperf_api.h
/usr/lib64/libiperf.so
/usr/share/man/man3/libiperf.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libiperf.so.0
/usr/lib64/libiperf.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iperf/035196a90af9ebe90871eb93aae845f5367247f3
/usr/share/package-licenses/iperf/2710606f6db128e7cf24e84572811bbf177a4ce9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/iperf3.1
